apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: 'credit-flow-application'
  description: 'Credit Flow monolithich for Red Hat Developer Hub'
  annotations:
    github.com/project-slug: maximilianopizarro/credit-flow-application
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-namespace: credit-flow-application-dev
    backstage.io/kubernetes-id: credit-flow-application
    janus-idp.io/tekton: credit-flow-application
    backstage.io/kubernetes-label-selector: 'app=credit-flow-application'
    backstage.io/swagger-api: 'https://github.com/maximilianopizarro/credit-flow-application/blob/main/openapi.yaml'
  links:
    - title: Documentation
      url: https://github.com/maximilianoPizarro/credit-flow-application/blob/main/README.md
    - url: https://workspaces.openshift.com/#https://github.com/maximilianoPizarro/credit-flow-application/tree/main?storageType=ephemeral
      title: OpenShift Dev Spaces (VS Code)
      icon: web
  tags:
    - java
    - dev
spec:
  type: service
  lifecycle: experimental
  owner: 'group:default/maximilianopizarro'
